spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hwangdonggeun70@gmail.com
    password: rctkswhovzhgkwdw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  #datasource:
    #url: jdbc:mysql://localhost:3306/testdb
    #username: root
    #password: 1234



#spring.datasource.url=jdbc:mysql://localhost:3306/testdb
#spring.datasource.username=root
#spring.datasource.password=1234
