spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hwangdonggeun70@gmail.com
    password: rctkswhovzhgkwdw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydatabase.cfw2ecc8mwzk.ap-northeast-2.rds.amazonaws.com:3306/goorm
    username: admin
    password: password
  server:
    port: 8080
    servlet:
      context-path: /
      encoding:
        charset: UTF-8
        enabled: true
        force: true








#datasource:
#url: jdbc:mysql://localhost:3306/testdb
    #username: root
    #password: 1234



#spring.datasource.url=jdbc:mysql://localhost:3306/testdb
#spring.datasource.username=root
#spring.datasource.password=1234